name: Conditional Pipeline and Deployment

on:
  push:
    branches:
      - '**'  # Trigger on push events from any branch

jobs:
  conditional-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # add any additional dependencies as needed

      - name: Run Pipeline if requested
        env:
            AWS_ACCESS_KEY_ID: "ASIA356SJTTCS3LW4FC2"
            AWS_SECRET_ACCESS_KEY: "OVDs33o5OQWMDtrZi7iKjykSBON42s9RHGtBg4e1"
            AWS_DEFAULT_REGION: "ca-central-1"
        if: contains(github.event.head_commit.message, '[RUN PIPELINES]')
        run: python run_pipeline.py

      - name: Deploy if requested
        env:
            AWS_ACCESS_KEY_ID: "ASIA356SJTTC35IPA6GE"
            AWS_SECRET_ACCESS_KEY: "trzIwZhaWDhBPUY/iuWTSAOTSKM5Ek3Tx6zXgL3J"
            AWS_DEFAULT_REGION: "ca-central-1"
        if: contains(github.event.head_commit.message, '[DEPLOY]')
        run: python deployment.py